function C = g_dynamics_C(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Apr-2021 16:16:51

q2 = in1(2,:);
v1 = in2(1,:);
v2 = in2(2,:);
t2 = sin(q2);
C = reshape([t2.*v2.*(-5.0./4.0),t2.*v1.*(5.0./4.0),t2.*(v1+v2).*(-5.0./4.0),0.0],[2,2]);
