function B = get_B_transv(s,s_dot,phi1,phi_prm1)
%GET_B_TRANSV
%    B = GET_B_TRANSV(S,S_DOT,PHI1,PHI_PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Apr-2021 16:16:53

B = [(s_dot.*-1.0e1)./(phi_prm1.*5.0+cos(phi1).*6.0+5.0);0.0;1.0];
