function A = get_A_transv(s,s_dot,phi1,phi_prm1,phi_2prm1)
%GET_A_TRANSV
%    A = GET_A_TRANSV(S,S_DOT,PHI1,PHI_PRM1,PHI_2PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    22-Apr-2021 14:52:49

t2 = phi_prm1.*5.0;
t3 = cos(phi1);
t4 = t3.*6.0;
t5 = t2+t4+5.0;
t6 = 1.0./t5;
t7 = sin(phi1);
t8 = phi1+s;
t9 = s_dot.^2;
A = reshape([s_dot.*t6.*(phi_2prm1.*5.0+t7.*6.0).*-2.0,0.0,0.0,s_dot.*t6.*(cos(t8).*9.8e1+t3.*t9.*5.0+(t7.*(sin(t8).*(4.9e1./2.0)+t9.*(phi_2prm1.*(2.5e1./2.4e1)+t7.*(5.0./4.0))).*5.0)./(phi_prm1.*(2.5e1./2.4e1)+t3.*(5.0./4.0)+2.5e1./2.4e1)).*(-1.2e1./5.0),0.0,0.0,0.0,1.0,0.0],[3,3]);
