function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    31-Mar-2021 12:05:44

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
Task = [q1;q2;cos(q1+q2+q3)./2.0+cos(q1+q2)./2.0+cos(q1)./2.0];
